package com.example.airline.model.enums;


public enum CountryEnum {

 Tirana("TIA- ALBANIA"),
 Yerevan("EVN-ARMENIA"),
 Vienna("VIE-AUSTRIA"),
 Baku("GYD-AZERBAIJAN"),
 Brussels("Charleroi-BELGIUM"),
 Banja("Luka -BOSNIA HERZEGOVINA"),
 Tuzla("TZL-Sarajevo"),
 Bourgas("Black Sea -BULGARIA"),
 Plovdiv("PDV -BULGARIA"),
 Sofia("SOF -BULGARIA"),
 Varna("Black Sea -BULGARIA"),
 Dubrovnik("DBV-CROATIA"),
 LarnacaL("CA-CYPRUS"),
 Prague("PRG-CZECH REPUBLIC"),
 Copenhagen("CPH-DENMARK"),
 Alexandria("Borg El Arab -EGYPT"),
 Cairo("Sphinx -EGYPT"),
 Hurghada("HRG -EGYPT"),
 SharmElSheik("SSH -EGYPT"),
 Tallinn("TLL-ESTONIA"),
 Turku("TKU-FINLAND"),
 Basel("MLH-FRANCE"),
 Lyon("LYS-FRANCE"),
 Nice("NCE-FRANCE"),
 Paris("PAR-FRANCE"),
 Kutaisi("KUT-GEORGIA"),
 Berlin("BER-GERMANY"),
 Bremen("BRE-GERMANY"),
 Frankfurt("HahnHHN-GERMANY"),
 Karlsruhe("Baden-BadenFKB-GERMANY"),
 Memmingen("Munich WestFMM-GERMANY"),
 Athens("ATH-GREECE"),
 Mykonos("JMK-GREECE"),
 Corfu("CFU-GREECE"),
 Heraklion("HER-GREECE"),
 Santorini("JTR-GREECE"),
 Thessaloniki("SKG-GREECE"),
 Zakynthos("ZTH-GREECE"),
 Budapest("BUD-HUNGARY"),
 Reykjavik("KEF-ICELAND"),
 Erbil("EBL-IRAQ"),
 TelAviv("TLV-ISRAEL"),
 Bologna("BLQ-ITALY"),
 Bari("BRI-ITALY"),
 Catania("GOA-ITALY"),
 Milan("Linate LIN-ITALY"),
 Naples("NAP-ITALY"),
 Pisa("PSA-ITALY"),
 Rome("ROM-ITALY"),
 Venice("VEN-ITALY"),
 Verona("VRN-ITALY"),
 Amman("AMM-JORDAN"),
 Almaty("ALA-KAZAKHSTAN"),
 Prishtina("PRN-KOSOVO"),
 Kuwait("KWI-KUWAIT"),
 Riga("RIX-LATVIA"),
 Kaunas("KUN-LITHUANIA"),
 Luxembourg("LUX-LUXEMBOURG"),
 //   Malé("Maldives MLE-MALDIVES"),
 Malta("MLA-MALTA"),
 Podgorica("TGD-MONTENEGRO"),
 Marrakesh("RAK-MOROCCO"),
 Eindhoven("EIN-NETHERLANDS"),
 Ohrid("OHD-NORTH MACEDONIA"),
 Skopje("SKP-NORTH MACEDONIA"),
 Oslo("OOS-NORWAY"),

 Muscat("MCT-OMAN"),
 Warsaw("Chopin WAW POLAND"),
 //    Kraków("KRK POLAND"),
 Lisbon("LIS-PORTUGAL"),
 Porto("OPO-PORTUGAL"),
 Bacau("BCM-ROMANIA"),
 Brasov("GHV-ROMANIA"),
 Timisoara("TSR-ROMANIA"),
 Dammam("DMM-SAUDI ARABIA"),
 Jeddah("JED-SAUDI ARABIA"),
 Belgrade("BEG-SERBIA"),
 //    Niš("INI-SERBIA"),
 Bratislava("BTS-SLOVAKIA"),
 Ljubljana("LJU-SLOVENIA"),
 Alicante("ALC-SPAIN"),
 Barcelona("El Prat BCN -SPAIN"),
 Castellon("Valencia CDT-SPAIN"),
 Fuerteventura("Canary Islands FUE SPAIN"),
 Ibiza("IBZ-SPAIN"),
 Madrid("MAD-SPAIN"),
 Malaga("AGP-SPAIN"),
 PalmadeMallorca("PMI-SPAIN"),
 Seville("SVQ-SPAIN"),
 Tenerife("Canary Islands TFS-SPAIN"),
 Valencia("VLC-SPAIN"),
 Gothenburg("Landvetter GOT-SWEDEN"),
 Stockholm("Arlanda ARN-SWEDEN"),
 Geneva("GVA-SWITZERLAND"),
 Ankara("ESB-TÜRKIYE"),
 Antalya("AYT-TÜRKIYE"),
 Istanbul("IST-TÜRKIYE"),
 AbuDhabi("AUH-UNITED ARAB EMIRATES"),
 Dubai("DXB-UNITED ARAB EMIRATES"),
 Birmingham("BHX- UNITED KINGDOM"),
 Bristol("BRS- UNITED KINGDOM"),
 Edinburgh("EDI- UNITED KINGDOM"),
 Liverpool("LPL- UNITED KINGDOM"),
 London("Luton LTN- UNITED KINGDOM"),
 Samarkand("SKD-UZBEKISTAN"),
 Tashkent("TAS-UZBEKISTAN");


 private final String country;

 CountryEnum(String country) {
  this.country = country;
 }

 public String getUrl() {
  return country;
 }


}

